### PR TITLE
Documentation around the ServiceAccount Annotation for secrets scenario

### PR DESCRIPTION
**Pull request by matthewmrichter**
Added per @Kami and @scalp42

### CODE REVIEW

**Comment by scalp42** [comment]
Thanks a lot @matthewmrichter, it'd be awesome if you could share bit more insights regarding the actual looking up of the secrets (assuming the pod has access to Parameter store/Secrets Manager with the right service account as you mentioned).

Cheers! 🏆

**Comment by matthewmrichter** [comment]
Since there are several ways to do a secrets lookup, I think we need to leave it to the end-users discretion, unfortuantely. It's really deployment-specific, and as we know with k8s, there can be a lot of different "right answers."

**Comment by scalp42** [comment]
Thanks for sharing!

We haven't been the biggest fans as it's been a bit clunky (see https://github.com/doitintl/secrets-init/issues/23). 

However, https://github.com/telia-oss/aws-env has been less prone to surprises in behavior, albeit it doesn't have the mutating bits.

Cheers 🙌

**Review by Kami — APPROVED** [review]

**Comment by Kami** [comment]
Merged, thanks!

**Pull request merged**
